theme = "jellybeans"

[editor]
color-modes = true
auto-completion = false
auto-format = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
]

[editor.lsp]
auto-signature-help = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'<' = '>'

[keys.normal."tab"]
s = ":write"
d = ":append-output date +'%%a %%d %%b %%Y'"
q = ":write-quit"
# TODO: Make it not macos specific
y = ":sh echo \"%{buffer_name}\" | pbcopy"
b = ":sh git blame -L %{cursor_line},+1 %{buffer_name}"
# Move a line to the bottom of a file. For marking as done in my todo lists
n = "@xdgep<C-o>"

[keys.insert]
C-space = "completion"
"C-[" = "normal_mode"
