[[language]]
name = "markdown"
text-width = 100
rulers = [101]

[[language]]
name = "html"
text-width = 100
rulers = [101]

[[language]]
name = "json"
formatter = {command = "jq", args = ["."]}

[[language]]
name = "xml"
formatter = {command = "xmllint", args = ["--format", "-"]}
